config/routes.rb
LotsoBear::Application.routes.draw do

  resources :supplier_types

  resources :type_likelihoods

  resources :services

  resources :stock_cars

  root 'sessions#new'

  resources :brands
  resources :mold_spares
  resources :model_acronyms
  resources :sessions, only: [:new, :create, :destroy]
  resources :prevaluations, only: [:new, :create, :show]
  resources :valuations, only: [:index, :new, :create, :show]
  resources :spares, only: [:index, :new, :create, :show, :edit ,:destroy, :update]
  resources :generic_spares, only: [:index, :new, :create, :show, :edit ,:destroy, :update]

  get '/supplies/consumer', to: 'supplies#consumer', as: 'consumer_supplies' #getting the user
  get '/supplies/spend/:user_code', to: 'supplies#spend', as: 'spend_fail_supplies' #supplies to spend are listed
  post '/supplies/spend', to: 'supplies#spend', as: 'spend_supplies' #supplies to spend are listed
  post '/supplies/add_supply_to_spend/', to: 'supplies#add_supply_to_spend', as:'add_supply_to_spend' #adds a single supply to spend via ajax
  post '/supplies/update_spend/', to:'supplies#update_spend', as: 'udpate_spend_supplies'
  resources :supplies do
  end

  get '/suppliers/:supplier_id/generic_families/:generic_family_id/new_supplier_code', to: 'supplier_codes#new', as: 'new_supplier_code'
  post '/suppliers/:supplier_id/generic_families/:generic_family_id/supplier_code_creation', to: 'supplier_codes#create', as: 'supplier_generic_family_supplier_codes'
  get '/suppliers/:supplier/add_supplier_codes/:generic_car', to: 'suppliers#add_codes', as: 'add_codes_supplier'
  get "/suppliers/:supplier/download_template/:generic_car", to: "suppliers#download_template", as: 'download_template'
  post "/:supplier/import/:generic_car", to: "suppliers#import", as: "import_suppliers"
  resources :suppliers do
  end

  get 'shelves/:code/store_stocks', to: 'shelves#store_stocks', as: 'get_store_stocks_shelf'

  get 'shelves/search', to: 'shelves#search', as: 'shelves_search'
  post 'shelves/store_stocks', to: 'shelves#store_stocks', as: 'store_stocks_shelf'
  post 'shelves/save_stocks', to: 'shelves#save_stocks', as: 'save_stocks_shelf'
  resources :warehouses do
      get 'shelves/new_bulk', to: 'shelves#new_bulk', as: 'shelves_bulk_new'
      post 'shelves/create_bulk', to: 'shelves#create_bulk', as: 'shelves_bulk_create'
      resources :shelves, shallow: true do
      end
  end

  post 'stock_families/print_label', to: 'stock_families#print_label', as: 'print_label_stock_family'
  post 'stock_families/search', to: 'stock_families#search', as: 'search_stock_family'
  resources :stock_families, only: [:index, :new, :show, :edit ,:destroy, :update] do
    member do
      post :print_label
      get :history
      get :choose_labels
    end
  end

  resources :stock_spares, only: [:edit,:show,:update] do
    member do
      get :history
    end
  end

  resources :orders do
    member do
      post :print_label
      get :history
    end
  end

  post 'generic_families/create_variant', to: 'generic_families#create_variant', as: 'create_variant_stock_family'
  get 'generic_families/:id/variant/:generic_car_id', to: 'generic_families#variant', as: 'variant_generic_family'
  get 'generic_families/:id/edit/:generic_car_id', to: 'generic_families#edit', as: 'edit_generic_family'
  get 'generic_families/remove/:id/', to: 'generic_families#destroy', as: 'delete_generic_family'

  resources :generic_families, only: [:index, :new, :create, :show, :destroy, :update] do
    collection do
      get :not_assigned
      get :assigned
      post :assign
    end
    member do
      get :count_spares
      get :prices
      get :assign_car_type
    end
  end

get "generic_cars/search_generic_car_models/:supplier", to: "generic_cars#search_by_model_in_supplier", as: 'search_by_model_in_supplier'
  resources :generic_cars do
    member do
      get :edit_generation
      get :assignation
      patch :relate_generic_family
      get :update_gen
    end
    collection do
      get :update_generation
      post :search_by_model
    end
  end

    get '/select_generic_families/:id', to: 'inventories#show_generic_car_generic_families', as: 'family_selection'
    get '/inventories/:family_id/:car_id/add_family_with_spares_to_order',to: 'inventories#add_family_with_spares_to_order'
  resources :inventories do
    member do
      get :add_family_with_spares_to_order
    end
    collection do
      get :departure
      get :all
      post :search_stock
      get :search_stock
      post :add_to_inventory, to: 'stock_families#create'
      post :departure_stock_family
      resources :stock_families, only: [:create]
      resources :supplies
    end
  end

  match '/consultar',            to: 'client_actions#home', via: 'get'
  match '/c/show',               to: 'client_actions#show', via: 'get'
  match '/get_client_car', to: 'client_actions#get_client_car', via: 'post'
  match '/admin/suppliers/',    to: 'suppliers#index',        via: 'get'
  match "/admin/attendance", to: 'admin#attendance', via: :get,  as: :attendances
  match '/user/update_attendances', to: 'users#update_attendances', via: :post, as: :import_attendances
  match '/user/:id/attendances', to: 'users#attendances', via: :get, as: :user_attendances

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/download_delays', to: 'users#download_delays', via: 'get', as: :download_delays
  resources :users do
    collection do
      get :spending
    end
    member do
      get :spending_history
    end
  end

namespace :admin do
    get :prices
end

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/views/admin/attendance.html.erb
<h1>Asistencias</h1>

    <%= form_tag import_attendances_path, multipart: true do %>
    	<h3>Escoge un archivo y despues de click en importar</h3>
      <%= file_field_tag :file %>
      <br>
      <%= submit_tag "Importar Archivo", class: "btn btn-primary" %>
    <% end %><h2>Usuarios registrados al reloj checador</h2>
<table class="table">
<thead>
	<th>Nombre</th>
	<th>Privilegios</th>
	<th>ID Reloj Checador</th>
	<th>Mes/Año</th>
	<th>Minutos Tarde</th>
	<th>Penalización</th>
	<th><%= link_to "Descargar Resumen Mensual", download_delays_path, class: "btn btn-primary" %>
	</th>
</thead>
<tbody>
	<% @users_with_clock.each do |user| %>
		<tr>
			<td><%= user.name %></td>
			<td><%= user.privileges %></td>
			<td><%= user.clock_id %></td>
			<td><%= "#{Date.today.month}/#{Date.today.year}" %></td>
			<td>
			<% if !user.delay_this_month(Date.today.month, Date.today.year).nil? %>
			<p> <%= user.delay_this_month(Date.today.month, Date.today.year) %> </p>
			<% else %>
				<p> No Hay Entradas de Este Mes </p>
			<% end %>
			</td>
			<td>
			<%= "MXN #{user.delay_this_month(Date.today.month, Date.today.year) * 35}"  unless user.delay_this_month(Date.today.month, Date.today.year).nil?  %>
			</td>
			<td><%= link_to "Meses Anteriores", user_attendances_path(user) %></td>
		</tr>
	<% end %>
</tbody>
</table>
<h2>Usuarios no registrados al reloj checador</h2>
<table class="table">
<thead>
	<th>Nombre</th>
	<th>Privilegios</th>
	<th></th>
</thead>
<tbody>
	<% @users_without_clock.each do |user| %>
		<tr>
			<td><%= user.name %></td>
			<td><%= user.privileges %></td>
			<td><%= link_to "Registrar ID", edit_user_path(user) %></td>
		</tr>
	<% end %>
</tbody>
</table>

app/views/admin/prices.html.erb
<h1>Administración de Precios</h1>

<h3>Familias sin Precio</h3>
<table class="table">
  <thead>
    <th>Nombre</th>
    <th>Código</th>
    <th>Modelo Coche</th>
    <th>Generación</th>
    <th>Precio</th>
  </thead>

  <tbody>
    <% for family in @families_unpriced %>
      <tr>
        <td><%= family.name %></td>
        <td><%= family.code  %></td>
        <td><%= family.generic_cars.first.model_acronym.model  %></td>
        <td><%= family.generic_cars.first.first_generation_year %> -
          <% if !family.generic_cars.first.gen_continues %>
            <%= family.generic_cars.first.last_generation_year %>
          <% else %>
            Año Actual
          <% end %>
         </td>
         <td>
           <%= link_to "Asignar Precio", prices_generic_family_path(family) %>
        </td>
      </tr>
    <% end %>
    </tbody>
</table>

<h3>Familias ya con precio</h3>
<table class="table">
  <thead>
    <th>Nombre</th>
    <th>Código</th>
    <th>Modelo Coche</th>
    <th>Generación</th>
    <th>Precio</th>
  </thead>

  <tbody>
    <% for family in @families_priced %>
      <tr>
        <td><%= family.name %></td>
        <td><%= family.code  %></td>
        <td><%= family.generic_cars.first.model_acronym.model  %></td>
        <td><%= family.generic_cars.first.first_generation_year %> -
          <% if !family.generic_cars.first.gen_continues %>
            <%= family.generic_cars.first.last_generation_year %>
          <% else %>
            Año Actual
          <% end %>
         </td>
         <td>
          $<%= family.supplier_codes.first.price %>
        </td>
      </tr>
    <% end %>
    </tbody>
</table>