config/routes.rb
LotsoBear::Application.routes.draw do

  resources :supplier_types

  resources :type_likelihoods

  resources :services

  resources :stock_cars

  root 'sessions#new'

  resources :brands
  resources :mold_spares
  resources :model_acronyms
  resources :sessions, only: [:new, :create, :destroy]
  resources :prevaluations, only: [:new, :create, :show]
  resources :valuations, only: [:index, :new, :create, :show]
  resources :spares, only: [:index, :new, :create, :show, :edit ,:destroy, :update]
  resources :generic_spares, only: [:index, :new, :create, :show, :edit ,:destroy, :update]

  get '/supplies/consumer', to: 'supplies#consumer', as: 'consumer_supplies' #getting the user
  get '/supplies/spend/:user_code', to: 'supplies#spend', as: 'spend_fail_supplies' #supplies to spend are listed
  post '/supplies/spend', to: 'supplies#spend', as: 'spend_supplies' #supplies to spend are listed
  post '/supplies/add_supply_to_spend/', to: 'supplies#add_supply_to_spend', as:'add_supply_to_spend' #adds a single supply to spend via ajax
  post '/supplies/update_spend/', to:'supplies#update_spend', as: 'udpate_spend_supplies'
  resources :supplies do
  end

  get '/suppliers/:supplier_id/generic_families/:generic_family_id/new_supplier_code', to: 'supplier_codes#new', as: 'new_supplier_code'
  post '/suppliers/:supplier_id/generic_families/:generic_family_id/supplier_code_creation', to: 'supplier_codes#create', as: 'supplier_generic_family_supplier_codes'
  get '/suppliers/:supplier/add_supplier_codes/:generic_car', to: 'suppliers#add_codes', as: 'add_codes_supplier'
  get "/suppliers/:supplier/download_template/:generic_car", to: "suppliers#download_template", as: 'download_template'
  post "/:supplier/import/:generic_car", to: "suppliers#import", as: "import_suppliers"
  resources :suppliers do
  end

  get 'shelves/:code/store_stocks', to: 'shelves#store_stocks', as: 'get_store_stocks_shelf'

  get 'shelves/search', to: 'shelves#search', as: 'shelves_search'
  post 'shelves/store_stocks', to: 'shelves#store_stocks', as: 'store_stocks_shelf'
  post 'shelves/save_stocks', to: 'shelves#save_stocks', as: 'save_stocks_shelf'
  resources :warehouses do
      get 'shelves/new_bulk', to: 'shelves#new_bulk', as: 'shelves_bulk_new'
      post 'shelves/create_bulk', to: 'shelves#create_bulk', as: 'shelves_bulk_create'
      resources :shelves, shallow: true do
      end
  end

  post 'stock_families/print_label', to: 'stock_families#print_label', as: 'print_label_stock_family'
  post 'stock_families/search', to: 'stock_families#search', as: 'search_stock_family'
  resources :stock_families, only: [:index, :new, :show, :edit ,:destroy, :update] do
    member do
      post :print_label
      get :history
      get :choose_labels
    end
  end

  resources :stock_spares, only: [:edit,:show,:update] do
    member do
      get :history
    end
  end

  resources :orders do
    member do
      post :print_label
      get :history
    end
  end

  post 'generic_families/create_variant', to: 'generic_families#create_variant', as: 'create_variant_stock_family'
  get 'generic_families/:id/variant/:generic_car_id', to: 'generic_families#variant', as: 'variant_generic_family'
  get 'generic_families/:id/edit/:generic_car_id', to: 'generic_families#edit', as: 'edit_generic_family'
  get 'generic_families/remove/:id/', to: 'generic_families#destroy', as: 'delete_generic_family'

  resources :generic_families, only: [:index, :new, :create, :show, :destroy, :update] do
    collection do
      get :not_assigned
      get :assigned
      post :assign
    end
    member do
      get :count_spares
      get :prices
      get :assign_car_type
    end
  end

get "generic_cars/search_generic_car_models/:supplier", to: "generic_cars#search_by_model_in_supplier", as: 'search_by_model_in_supplier'
  resources :generic_cars do
    member do
      get :edit_generation
      get :assignation
      patch :relate_generic_family
      get :update_gen
    end
    collection do
      get :update_generation
      post :search_by_model
    end
  end

    get '/select_generic_families/:id', to: 'inventories#show_generic_car_generic_families', as: 'family_selection'
    get '/inventories/:family_id/:car_id/add_family_with_spares_to_order',to: 'inventories#add_family_with_spares_to_order'
  resources :inventories do
    member do
      get :add_family_with_spares_to_order
    end
    collection do
      get :departure
      get :all
      post :search_stock
      get :search_stock
      post :add_to_inventory, to: 'stock_families#create'
      post :departure_stock_family
      resources :stock_families, only: [:create]
      resources :supplies
    end
  end

  match '/consultar',            to: 'client_actions#home', via: 'get'
  match '/c/show',               to: 'client_actions#show', via: 'get'
  match '/get_client_car', to: 'client_actions#get_client_car', via: 'post'
  match '/admin/suppliers/',    to: 'suppliers#index',        via: 'get'
  match "/admin/attendance", to: 'admin#attendance', via: :get,  as: :attendances
  match '/user/update_attendances', to: 'users#update_attendances', via: :post, as: :import_attendances
  match '/user/:id/attendances', to: 'users#attendances', via: :get, as: :user_attendances

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/download_delays', to: 'users#download_delays', via: 'get', as: :download_delays
  resources :users do
    collection do
      get :spending
    end
    member do
      get :spending_history
    end
  end

namespace :admin do
    get :prices
end

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/supply.rb
class Supply < ActiveRecord::Base
	belongs_to :supplier
	has_many :spendings

	validates :name, :minimum_qty, :cost, :description, :quantity,  :code, presence: true
  	validates :code, uniqueness: true

end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action :set_supply, only: [:show, :edit, :update, :destroy]

  # GET /supplies
  # GET /supplies.json
  def index
    @supplies = Supply.all
  end

  # GET /supplies/1
  # GET /supplies/1.json
  def show
  end

  # GET /supplies/new
  def new
    @supply = Supply.new
  end

  # GET /supplies/1/edit
  def edit
  end

# <Process Spend Supply>
  def consumer
  end

  def spend
    @employee = User.find_by_code(params[:user_code])

    if @employee.blank?
      flash[:danger] = "Empleado no encontrado"
      redirect_to consumer_supplies_path
    end
  end

  def add_supply_to_spend
    @supply = Supply.find_by_code(params[:supply_code])
      respond_to do |format|
      format.js {}
    end
  end

  def update_spend
    supplies = params[:supplies]
      supplies.each do |supply_info|
        supply = Supply.find_by_id(supply_info[:supply_id])
        if supply_info[:supply_quantity_to_spend].blank?
          flash[:danger] = "Error, no se pueden poner cantidades vacias"
          redirect_to spend_fail_supplies_path(params[:user_code])
          return 0
        elsif supply.quantity-supply_info[:supply_quantity_to_spend].to_i < 0
          flash[:danger] = "#{supply.name} se ha agotado, solo quedan #{supply.quantity}, vuelva a empezar el proceso."
          redirect_to spend_fail_supplies_path(params[:user_code])
          return 0
        else
          user = User.find_by_code(params[:user_code])
          Supply.transaction do
            supply.update(quantity:supply.quantity-supply_info[:supply_quantity_to_spend].to_i)
            Spending.create_with_cost(user,supply,supply_info[:supply_quantity_to_spend])  
          end
        end
      end
      flash[:success] = "Cantidades Actualizadas con exito"
      redirect_to consumer_supplies_path
  end
    
# </Process Spend Supply>


  # POST /supplies
  # POST /supplies.json
  def create
    @supply = Supply.new(supply_params)

    respond_to do |format|
      if @supply.save
        format.html { redirect_to @supply, notice: 'Supply was successfully created.' }
        format.json { render action: 'show', status: :created, location: @supply }
      else
        format.html { render action: 'new' }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1
  # PATCH/PUT /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to @supply, notice: 'Supply was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1
  # DELETE /supplies/1.json
  def destroy
    @supply.destroy
    respond_to do |format|
      format.html { redirect_to supplies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supply_params
      params.require(:supply).permit(:name, :minimum_qty, :cost, :description, :quantity, :weight, :supplier_id, :brand, :size, :code 
        )
    end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.erb
<%= form_for(@supply) do |f| %>
  <% if @supply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supply.errors.count, "error") %> prohibited this supply from being saved:</h2>

      <ul>
      <% @supply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div  class="col-md-6">

    <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :minimum_qty %><br>
    <%= f.number_field :minimum_qty %>

  </div>  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>  

</div>
      
  <div class="col-md-6">
    <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <br>
  <div>
    <%= grouped_collection_select :supply, :supplier_id, SupplierType.all, :suppliers, :name, :id, :name, :include_blank => true %>
  </div>
  </div>
  <br>
  <div class="col-md-12 center-block">
    <br>
    <div class="actions">
    <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/supplies/_single_supply.html.erb
<tr>
	<td><%= @supply.name %></td>
	<td><%= @supply.code %></td>
	<td><%= @supply.brand %></td>
	<td><%= @supply.size %></td>
	<td><%= @supply.quantity %></td>
	<td><%= number_field_tag "supplies[][supply_quantity_to_spend]",nil %></td>
	<td class="hidden"><%= hidden_field_tag "supplies[][supply_id]", @supply.id  %></td>
</tr>

app/views/supplies/add_supply_to_spend.js.erb
$('#supplies_to_spend').append('<%=j render "single_supply"%>');
$('#supply_code').val('').focus();

app/views/supplies/consumer.html.erb
<h1>Escanea tu Codigo: </h1>

<%= form_tag spend_supplies_path do %>
	<%= text_field_tag :user_code %>
	<%= submit_tag "Buscar Empleado" %>
<% end %>

app/views/supplies/edit.html.erb
<h1>Editing supply</h1>

<%= render 'form' %>

<%= link_to 'Show', @supply %> |
<%= link_to 'Back', supplies_path %>

app/views/supplies/index.html.erb
<h1> Consumibles </h1>

<table class="table">
  <thead class="">
    <tr>
      <th>Nombre</th>
      <th>Cantidad Mínima</th>
      <th>Costo</th>
      <th>Descripción</th>
      <th>Peso</th>
      <th>Marca</th>
      <th>Cantidad</th>
      <th>Tamaño</th>
      <th>Proveedor</th>
      <th>Codigo</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @supplies.each do |supply| %>
      <tr>
        <td><%= supply.name %></td>
        <td><%= supply.minimum_qty %></td>
        <td><%= supply.cost %></td>
        <td><%= supply.description %></td>
        <td><%= supply.weight %></td>
        <td><%= supply.brand %></td>
        <td><%= supply.quantity %></td>
        <td><%= supply.size %></td>
        <td>
          <% unless supply.supplier.blank? %>
            <%= supply.supplier.name %>
          <% end %>
        </td>
        <td><%= supply.code %></td>
        <td><%= link_to 'Editar', edit_supply_path(supply),class:"btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', supply, method: :delete, data: { confirm: '¿Estas Seguro?' },class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Consumible', new_supply_path, class:"btn btn-success" %>

app/views/supplies/new.html.erb
<h1>New supply</h1>

<%= render 'form' %>

<div class="col-md-12">
	<br>
<%= link_to 'Back', supplies_path %>
</div>

app/views/supplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @supply.name %>
</p>

<p>
  <strong>Minimum qty:</strong>
  <%= @supply.minimum_qty %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @supply.cost %>
</p>

<p>
  <strong>Description:</strong>
  <%= @supply.description %>
</p>

<%= link_to 'Edit', edit_supply_path(@supply),class:"btn btn-info" %> |
<%= link_to 'Back', supplies_path,class:"btn btn-default" %>

app/views/supplies/spend.html.erb
<table class="table">
	<thead>
		<tr>
			<th>Nombre</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @employee.name %></td>
		</tr>
	</tbody>
</table>

<%= form_tag add_supply_to_spend_path, remote: true do %>
	<%= text_field_tag :supply_code %>
	<%= submit_tag "Buscar Consumible" %>
<% end %>

<%= form_tag udpate_spend_supplies_path do %>
	<%= hidden_field_tag :user_code, @employee.code  %>
	<table class="table">
		<thead>
			<tr>
				<th>Nombre</th>
				<th>Codigo</th>
				<th>Marca</th>
				<th>Tamaño</th>
				<th>Existencia</th>
				<th>Cantidad a gastar</th>
			</tr>
		</thead>
		<tbody id="supplies_to_spend">

		</tbody>
	</table>
	<%= submit_tag "Introducir Gastos" %>
<% end %>