config/routes.rb
LotsoBear::Application.routes.draw do

  resources :supplier_types

  resources :type_likelihoods

  resources :services

  resources :stock_cars

  root 'sessions#new'

  resources :brands
  resources :mold_spares
  resources :model_acronyms
  resources :sessions, only: [:new, :create, :destroy]
  resources :prevaluations, only: [:new, :create, :show]
  resources :valuations, only: [:index, :new, :create, :show]
  resources :spares, only: [:index, :new, :create, :show, :edit ,:destroy, :update]
  resources :generic_spares, only: [:index, :new, :create, :show, :edit ,:destroy, :update]

  get '/supplies/consumer', to: 'supplies#consumer', as: 'consumer_supplies' #getting the user
  get '/supplies/spend/:user_code', to: 'supplies#spend', as: 'spend_fail_supplies' #supplies to spend are listed
  post '/supplies/spend', to: 'supplies#spend', as: 'spend_supplies' #supplies to spend are listed
  post '/supplies/add_supply_to_spend/', to: 'supplies#add_supply_to_spend', as:'add_supply_to_spend' #adds a single supply to spend via ajax
  post '/supplies/update_spend/', to:'supplies#update_spend', as: 'udpate_spend_supplies'
  resources :supplies do
  end

  get '/suppliers/:supplier_id/generic_families/:generic_family_id/new_supplier_code', to: 'supplier_codes#new', as: 'new_supplier_code'
  post '/suppliers/:supplier_id/generic_families/:generic_family_id/supplier_code_creation', to: 'supplier_codes#create', as: 'supplier_generic_family_supplier_codes'
  get '/suppliers/:supplier/add_supplier_codes/:generic_car', to: 'suppliers#add_codes', as: 'add_codes_supplier'
  get "/suppliers/:supplier/download_template/:generic_car", to: "suppliers#download_template", as: 'download_template'
  post "/:supplier/import/:generic_car", to: "suppliers#import", as: "import_suppliers"
  resources :suppliers do
  end

  get 'shelves/:code/store_stocks', to: 'shelves#store_stocks', as: 'get_store_stocks_shelf'

  get 'shelves/search', to: 'shelves#search', as: 'shelves_search'
  post 'shelves/store_stocks', to: 'shelves#store_stocks', as: 'store_stocks_shelf'
  post 'shelves/save_stocks', to: 'shelves#save_stocks', as: 'save_stocks_shelf'
  resources :warehouses do
      get 'shelves/new_bulk', to: 'shelves#new_bulk', as: 'shelves_bulk_new'
      post 'shelves/create_bulk', to: 'shelves#create_bulk', as: 'shelves_bulk_create'
      resources :shelves, shallow: true do
      end
  end

  post 'stock_families/print_label', to: 'stock_families#print_label', as: 'print_label_stock_family'
  post 'stock_families/search', to: 'stock_families#search', as: 'search_stock_family'
  resources :stock_families, only: [:index, :new, :show, :edit ,:destroy, :update] do
    member do
      post :print_label
      get :history
      get :choose_labels
    end
  end

  resources :stock_spares, only: [:edit,:show,:update] do
    member do
      get :history
    end
  end

  resources :orders do
    member do
      post :print_label
      get :history
    end
  end

  post 'generic_families/create_variant', to: 'generic_families#create_variant', as: 'create_variant_stock_family'
  get 'generic_families/:id/variant/:generic_car_id', to: 'generic_families#variant', as: 'variant_generic_family'
  get 'generic_families/:id/edit/:generic_car_id', to: 'generic_families#edit', as: 'edit_generic_family'
  get 'generic_families/remove/:id/', to: 'generic_families#destroy', as: 'delete_generic_family'

  resources :generic_families, only: [:index, :new, :create, :show, :destroy, :update] do
    collection do
      get :not_assigned
      get :assigned
      post :assign
    end
    member do
      get :count_spares
      get :prices
      get :assign_car_type
    end
  end

get "generic_cars/search_generic_car_models/:supplier", to: "generic_cars#search_by_model_in_supplier", as: 'search_by_model_in_supplier'
  resources :generic_cars do
    member do
      get :edit_generation
      get :assignation
      patch :relate_generic_family
      get :update_gen
    end
    collection do
      get :update_generation
      post :search_by_model
    end
  end

    get '/select_generic_families/:id', to: 'inventories#show_generic_car_generic_families', as: 'family_selection'
    get '/inventories/:family_id/:car_id/add_family_with_spares_to_order',to: 'inventories#add_family_with_spares_to_order'
  resources :inventories do
    member do
      get :add_family_with_spares_to_order
    end
    collection do
      get :departure
      get :all
      post :search_stock
      get :search_stock
      post :add_to_inventory, to: 'stock_families#create'
      post :departure_stock_family
      resources :stock_families, only: [:create]
      resources :supplies
    end
  end

  match '/consultar',            to: 'client_actions#home', via: 'get'
  match '/c/show',               to: 'client_actions#show', via: 'get'
  match '/get_client_car', to: 'client_actions#get_client_car', via: 'post'
  match '/admin/suppliers/',    to: 'suppliers#index',        via: 'get'
  match "/admin/attendance", to: 'admin#attendance', via: :get,  as: :attendances
  match '/user/update_attendances', to: 'users#update_attendances', via: :post, as: :import_attendances
  match '/user/:id/attendances', to: 'users#attendances', via: :get, as: :user_attendances

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/download_delays', to: 'users#download_delays', via: 'get', as: :download_delays
  resources :users do
    collection do
      get :spending
    end
    member do
      get :spending_history
    end
  end

namespace :admin do
    get :prices
end

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/generic_family.rb
# -*- encoding : utf-8 -*-
class GenericFamily < ActiveRecord::Base

  has_many :childs, class_name: 'GenericFamily', foreign_key: 'father_id'
  belongs_to :father, class_name: 'GenericFamily'

  has_many :variants, class_name: 'GenericFamily', foreign_key: 'original_id'
  belongs_to :original, class_name: 'GenericFamily'

  has_many :spare_likelihoods, dependent: :destroy
  has_many :generic_spares, -> { order 'code' }, through: :spare_likelihoods, dependent: :destroy

  has_many :stock_families, dependent: :destroy

  has_many :type_likelihoods, dependent: :destroy
  has_many :car_types, through: :type_likelihoods

  has_many :family_likelihoods, dependent: :destroy
  has_many :generic_cars, through: :family_likelihoods

  has_many :suppliers, through: :supplier_codes
  has_many :supplier_codes, dependent: :destroy

  has_many :generic_family_images

  accepts_nested_attributes_for :generic_spares
  accepts_nested_attributes_for :spare_likelihoods, allow_destroy: true

  validates :name, presence: :true
  validates :code, presence: :true
  attr_accessor :generic_car_id

  after_save :delete_empty_spare_likelihoods
              
  def delete_empty_spare_likelihoods
    spare_likelihoods.each do |spare_likelihood|
      if spare_likelihood.generic_family_id.blank? or spare_likelihood.generic_spare_id.blank?
        spare_likelihood.delete
      end
    end
  end
# Clones of a generic_families to all the generic_cars that have the same car_type as the parameter. 
# Params:
# +type_likelihood+:: +TypeLikelihood+ object from which to extract the generic family and car_type
  def self.add_to_corresponding_cars (type_likelihood)
    ActiveRecord::Base.transaction do
      # Select all the cars with the car_type of the type_likelihood_parameter
      generic_cars = GenericCar.where(car_type_id:type_likelihood.car_type_id)
      # Selects the family  from the type_likelihood parameter
      family = type_likelihood.generic_family
      # Clones a generic_family. Relates the clone to each generic_car
      generic_cars.each do |generic_car|
        # Clone the family with generic spares
        clone = family.clone_generic_family_with_generic_spares
        clone.years = generic_car.formatted_year
        unless clone.blank?
          # Relates the clone to a generic_car
          generic_car.generic_families << clone
        end
      end
    end
  end

# Searches generic_families that haven´t been related to the given generic_car 
# Params:
# +spares_info+:: +Array+ containing hashes with spare info (a hash has an id +Integer+ from a generic_spare, +String+ supplier_code, +String+ color), 
# +car_id+:: +Integer+ object Integer of a GenericCar (The one that was specified in a order)
# Returns A StockFamily
  def generate_stock_family_with_stock_spares (spares_info, car_id)
    #  New empty StockFamily
    stockFam = StockFamily.new
    # Assign the original id to the clone (Its father)
    stockFam.generic_family_id = self.id
    # Assign the id of the given GenericCar
    stockFam.car_order_id = car_id
  # Check that the spare info isn´t empty  
    unless spares_info.blank?
      # Loop each hash
      spares_info.each do |spare_tuple|
        # Check the hash isn´t empty
        unless spare_tuple[:id].blank?
          # New empty StockSpare
          spare = StockSpare.new
          # Relate spare to a Generic Spare
          spare.generic_spare_id = spare_tuple[:id]
          # Add supplier code (String)
          spare.supplier_code = spare_tuple[:supplier_code]
          # Update Status 
          spare.status = "Almacen"
          # Add the new StockSpare to the StockFamily
          stockFam.stock_spares << spare
        end
      end
    end
    # Return a StockFamily
    stockFam
  end

# Interpolates the name and code of self
# Returns: a string
  def name_with_code
    "#{self.name}, #{self.code}"
  end

# Clones a GenericFamily including the GenericSpares it contains. 
# Returns A GenericFamily 
  def clone_generic_family_with_generic_spares
    clone = self.dup
    self.generic_spares.each do | spare|
      clone_spare = spare.dup
      clone_spare.father_id = spare.id
      clone.generic_spares << clone_spare
    end
    clone.father = self
    clone
  end

    def get_supplier_code(supplier)
    supplier_code = SupplierCode.where(generic_family_id: self.id, supplier_id: supplier.id)
    unless supplier_code.blank?
      supplier_code.first.code
    end
  end

  def get_price(supplier)
    supplier_code = SupplierCode.where(generic_family_id: self.id, supplier_id: supplier.id)
    supplier_code.first.price
  end

  def has_supplier_code?(supplier)
    supplier_code = SupplierCode.where(generic_family_id: self.id, supplier_id: supplier.id)
    if supplier_code.blank?
      return false
    else
      return true
    end
  end


  # // QUERIES //
# Searches all generic families that have not been related to a Typelikehood (Families that don´t have a car_type)
# Returns Array of GenericFamily
  def self.not_assigned_families
    where.not(:id  => TypeLikelihood.select(:generic_family_id)).where(father_id: nil)
  end

# Searches all generic families that have been related to a Typelikehood (Families that have a car_type)
# Returns Array of GenericFamily
  def self.assigned_families
    where(:id  => TypeLikelihood.select(:generic_family_id) ).where(father_id: nil)
  end

# Searches generic_families that haven´t been related to the given generic_car 
# Params:
# +generic_car+:: +GenericCar+ object
# Returns Array of GenericFamily
  def self.other_families(generic_car)
    # If the generic car doesn´t have any generic families Return all the GenericFamilies
    if generic_car.generic_families.empty?
      all
    else
      # Query that fidns all families that are not related to the generic_car
      where('id not in (?)', generic_car.generic_families.pluck(:id).concat(generic_car.generic_families.pluck(:father_id)).compact).where(father_id: nil)
    end
  end

# Searches all generic families that match by name, code or generic_car model
# Params:
# +generic_car+:: +String+ model of a generic_car
# +generic_family+:: +String+ name of a generic_family
# Returns Array of GenericFamilys
  def self.search(generic_family, generic_car)
    if !generic_family.blank? && !generic_car.blank?
      generic_families = GenericFamily.joins(generic_cars: :model_acronym).where("lower(name) LIKE ? OR lower(code) like ?","%#{generic_family.downcase}%", "%#{generic_family.downcase}%").where( model_acronyms: {model: generic_car.upcase})
    elsif generic_family.blank?
      generic_families = GenericFamily.joins(generic_cars: :model_acronym).where( model_acronyms: {model: generic_car.upcase})
    else
      generic_families = GenericFamily.where("lower(name) LIKE ? OR lower(code) like ?","%#{generic_family.downcase}%", "%#{generic_family.downcase}%")
    end
    generic_families
  end

# Searches all generic families that are not related to the supplier
# Params:
# +supplier+:: +Supplier+ object
# Returns Array of GenericFamilys
  def self.without_supplier_code(supplier)
    # joins(:supplier_codes).where( supplier_codes: {supplier_id: supplier.id})
    where.not(father_id: nil).limit 500
  end
end

app/controllers/generic_families_controller.rb
class GenericFamiliesController < ApplicationController
  before_action :set_family, only: [:show, :destroy, :edit, :count_spares, :prices, :update, :assign_car_type]

  def new
    @generic_family = GenericFamily.new
    @generic_family.spare_likelihoods.build.build_generic_spare
  end

  def create
    @generic_family = GenericFamily.new(required_params)
    if @generic_family.save
      redirect_to generic_families_path
      unless @generic_family.generic_spares.blank?
        flash[:success] = "Familia: <strong>#{@generic_family.name}</strong>, con piezas: #{@generic_family.generic_spares.pluck(:name).join(', ').tr('[]', '')} creada con éxito".html_safe
      else
        flash[:success] = "Familia: <strong>#{@generic_family.name}</strong> creada con éxito".html_safe
      end
    else
      render 'new'
    end
  end

  def update
    @generic_car = GenericCar.find_by_id(params[:generic_family][:generic_car_id])
    respond_to do |format|
      if @generic_family.update(required_params)
        format.html { redirect_to assignation_generic_car_path( @generic_car.id ), notice: 'Guardado con éxito' }
      else
        format.html { render :edit }
      end
    end
  end


# <CREATE VARIANT>
  def variant
    @generic_family_father = GenericFamily.find_by_id(params[:id])
    @generic_car = GenericCar.find_by_id(params[:generic_car_id])
    @generic_family = GenericFamily.new
    @generic_family.father_id = @generic_family_father.id
    @generic_family.name ||= @generic_family_father.name
    @generic_family.code ||= @generic_family_father.code

    @generic_family_father.generic_spares.each do |generic_spare|
      pre_build = @generic_family.spare_likelihoods.build
      build = pre_build.build_generic_spare
      build.name = generic_spare.name
      build.code = generic_spare.code
    end
  end

  def create_variant
    @generic_car = GenericCar.find_by_id(params[:generic_car_id])
    generic_family_father = GenericFamily.find_by_id(params[:generic_family_father])

    variant_family = generic_family_father.clone_generic_family_with_generic_spares
    variant_family.original_id = generic_family_father.id
    variant_family.name ="#{variant_family.name}-#{params[:code]}" 
    variant_family.code ="#{variant_family.code}-#{params[:code]}"
    variant_family.years = params[:years]
    variant_family.variant_comment = params[:comment]
    variant_family.generic_spares.each do |generic_spare|
      generic_spare.code = "#{generic_spare.code}-#{params[:code]}"
    end
    @generic_car.generic_families << variant_family
    if @generic_car.save!
      flash[:success] = "Guardado con éxito"
      redirect_to edit_generic_family_path(variant_family,@generic_car)
    end
  end
# </CREATE VARIANT>


# <RELATE FAMILY TO CARTYPES>
  def assign_car_type
    @car_types = CarType.all
  end
# </RELATE FAMILY TO CARTYPES>
  def prices
  end

  def show
    @generic_car = GenericCar.find_by_id(params[:format])
  end

  def index
    @generic_families = GenericFamily.all.where(father_id: nil)
  end

  def edit
    @generic_car = GenericCar.find_by_id(params[:generic_car_id])
  end

  def destroy
    @generic_family.destroy
    flash[:danger] = "#{@generic_family.name} borrada con éxito"
    redirect_to action: 'index'
  end

  def assigned
    @generic_families_assigned = GenericFamily.assigned_families
    @generic_families_not = GenericFamily.not_assigned_families
    @car_types = CarType.all
  end

  def assign
    family = params[:family_ids]
    unless family.blank?
      family.each do | f |
        family_id = f.split(',')[0].to_i
        type_id = f.split(',')[1].to_i
        type_likelihood = TypeLikelihood.new(generic_family_id: family_id, car_type_id:type_id)
        if type_likelihood.save
          GenericFamily.add_to_corresponding_cars(type_likelihood)
        end
      end
      flash[:success] = "Actualizado con éxito"
    end
    redirect_to assigned_generic_families_path
  end



  private
    def required_params
      params.require(:generic_family).permit(:generic_car_id,:code,:name, :years, {:types => []},{:family_ids => []} ,spare_likelihoods_attributes:[:id, :generic_family_id, :generic_spare_id, :_destroy, generic_spare_attributes:[:id, :name,:code, :_destroy]])
    end

    def set_family
      @generic_family = GenericFamily.find_by_id(params[:id])
    end

end

app/helpers/generic_families_helper.rb
# -*- encoding : utf-8 -*-
module GenericFamiliesHelper

	def build_spares_for_families(family, number)
		number.times {family.generic_spares.build}
	end
end

app/views/generic_families/_form.html.erb
<%= form_for @generic_family do |f| %>
	<%= render 'shared/error_messages' , model: @generic_family %>

	<%= f.hidden_field :id%>
	<div class="row">
		<div class='col-md-4'>
			<div class='form-group'>
				<%= f.label :name %>
				<%= f.text_field :name, :class =>"form-control"%>
			</div>
		</div>
		<div class='col-md-4'>
			<div class='form-group'>
				<%= f.label :code %>
				<%= f.text_field :code, class:"form-control"%>
			</div>
		</div>


		<div class='col-md-4'>
			<div class='col-md-6'>
				<%= label_tag :number_spares, "Número de Piezas" %>
				<%= number_field_tag :number_spares, min: 1, max: 50 , class: "form-control"%>
			</div>
			<div class='col-md-6'>
				<br>
				<%= link_to 'Agregar Piezas', '#', class: "btn btn-info", id: 'creator' %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<h2>Piezas</h2>
			<div id="family_members" class="col-md-8">
		<%= f.fields_for :spare_likelihoods do | likelihood | %>
			<%= likelihood.fields_for :generic_spare do | spare | %>
			<% end %>

		<% end %>
	</div>

	</div>
	</div>
<div class="row">
	<div class="col-md-6"></div>
	<div class="col-md-3"><%= link_to t(:cancel), generic_families_path, class: "btn btn-default" %>
</div>
	<div class="col-md-3"><%= f.submit class: "btn btn-primary"%>
</div>


</div>
<% end %>

<script type="text/javascript">
	var contador=0;

	$.ajax({
		url: "/generic_families/"+$("#generic_family_id").val()+"/count_spares",
	}).done(function(number_of_spares) {
		console.log(number_of_spares.count);


		contador = number_of_spares.count;

	});

	$("#creator").click(function() {
    	var val =     $("#number_spares").val();
		var code = $("#generic_family_code").val()
		if (!code){
			alert("Codigo no puede estar Vacio");
		}
		else{
	    	for (i=0;i < $("#number_spares").val(); i++)
	    	{
	        	$("#family_members").append('<div class="form-group"><div class="col-md-6"><label for="generic_family_spare_likelihoods_attributes_'+contador+'_generic_spare_attributes_name">Nombre Pieza '+contador+'</label><input class="form-control input-capitalize" id="generic_family_spare_likelihoods_attributes_'+contador+'_generic_spare_attributes_name" name="generic_family[spare_likelihoods_attributes]['+contador+'][generic_spare_attributes][name]" type="text"></div><div class="col-md-3"><label>Código</label><input class="form-control hidden" id="generic_family_spare_likelihoods_attributes_'+contador+'_generic_spare_attributes_code" name="generic_family[spare_likelihoods_attributes]['+contador+'][generic_spare_attributes][code]" type="text" value="'+$("#generic_family_code").val()+contador+'"><p>'+code+contador+'</p></div></div>');
	        	contador++;
	    	}
		}
    });

</script>

app/views/generic_families/_spare_likelihood_fields.html.erb
<div class="col-md-12 nested-fields spare_likelihoods">
	<%= f.fields_for :generic_spare do | spare | %>
		<%= render 'generic_spare_fields', :f => spare %>
	<% end %>
	<div class="col-md-3">
		<label>Quitar Pieza</label><br>
		<%= link_to_remove_association "X", f , class: 'btn btn-danger' %>
	</div>
</div>

app/views/generic_families/assign_car_type.html.erb
<h1>Asignación de Tipos de Coche</h1>

<%= form_tag assign_generic_families_path do | f | %>

	<table id="assignation_table" class="table">
	    <thead>
	        <tr>
	            <th>Nombre Familia</th>
	            <% @car_types.each do | type | %>
	            	<th><%= type.name %><%= type.doors %></th>
	            <% end %>
	        </tr>
	    </thead>
	    <tbody>
		    <tr>
		        <td><%= @generic_family.name %></td>
		        <% for type in @car_types do %>
		           	<% if type.generic_families.select { |fam| fam.id == @generic_family.id}.include? @generic_family  %>
		           		<td><%= check_box_tag 'family_ids[]', "#{@generic_family.id},#{type.id}", checked: true %></td>
		           	<% else %>
		           		<td><%= check_box_tag 'family_ids[]', "#{@generic_family.id},#{type.id}"%></td>
		           	<% end %>
	           	<% end %>
	 		</tr>
    	</tbody>
	</table>


	<%= submit_tag "Guardar Familia", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
	$('#assignation_table').DataTable({});
</script>

app/views/generic_families/assigned.html.erb
<h1>ASIGNACIÓN DE FAMILIAS A TIPOS DE VEHÍCULOS</h1>
<h2>Familia ya asignadas</h2>
<table id="assigned" class="table big_table">
	<thead>
		<tr>
			<th>Nombre Familia</th>
			<% @car_types.each do | type | %>
				<th> <%= type.name %> <%= type.doors %></th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% @generic_families_assigned.each do | family | %>
			<tr>
				<td>
					<%= family.name %><br>
					<%= link_to "Editar Tipos",  assign_car_type_generic_family_path(family), class: "btn btn-primary" %>
				</td>
				<% for type in @car_types do %>
					<% if type.generic_families.select { |fam| fam.id == family.id}.include? family  %>
				<td><p>x</p></td>
				<% else %>
				<td><p>--</p></td>
				<% end %>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>
<h2>Familias sin asignación</h2>
<table id="not_assigned" class="table">
	<thead>
		<th>Nombre Familia</th>
		<th></th>
	</thead>
	<tbody>
		<% @generic_families_not.each do | family | %>
			<tr>
				<td><%= family.name %></td>
				<td><%= link_to "Asignar Tipos de Coche", assign_car_type_generic_family_path(family), class: "btn btn-primary" %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<script type="text/javascript">
$('#not_assigned').DataTable({});
$('#assigned').DataTable({});
</script>

app/views/generic_families/assigned_families.html.erb
<h1>Familias genéricas</h1>


<%= form_tag assign_generic_families_path do | f | %>

	<table id="assignation_table" class="table big_table">
	    <thead>
	        <tr>
	            <th>Nombre Familia</th>
	            <% @car_types.each do | type | %>
	            	<th> <%= type.name %> <%= type.doors %></th>
	            <% end %>
	        </tr>
	    </thead>
	    <tbody>

	    <!-- each family -->
			    <% @generic_families.each do | family | %>
			    	<tr>

			           <td><%= family.name %></td>
			           <% for type in @car_types do %>

			           	<% if type.generic_families.select { |fam| fam.id == family.id}.include? family  %>
			           		<td><%= check_box_tag 'family_ids[]', "#{family.id},#{type.id}", checked: true %></td>
			           	<% else %>
			           		<td><%= check_box_tag 'family_ids[]', "#{family.id},#{type.id}"%></td>
			           	<% end %>

			           <% end %>
		 		  </tr>
			    <% end %>



    	</tbody>
	</table>


	<%= submit_tag "Guardar Cambios", class: "btn btn-primary"  %>
<% end %>

app/views/generic_families/edit.html.erb
<h1>Editar Familia</h1>


<%= render 'form_edit' %>

app/views/generic_families/index.html.erb
<div class='row'>
  <div class='col-md-12'>
    <h1><%= GenericFamily.model_name.human(count:2) %></h1>
  </div>
  <div class="col-md-6"></div>
  <div class='col-md-6'>
  <%= link_to "Nueva Familia", new_generic_family_path, class: "btn btn-primary"%>
  <%= link_to "Asignar Nuevas Familias", not_assigned_generic_families_path, class: "btn btn-primary"%>
  <%= link_to "Ver Familias Asignadas", assigned_generic_families_path, class: "btn btn-primary"%>
  </div>

  <div class='col-md-12'>
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>
          <%= t(:name) %>
          </th>
          <th>
          <%= t(:code) %>
          </th>
          <th>
          <%= t(:number_of_spares) %>
          </th>
          <th>
          <%= t(:show) %>
          </th>
          <th>
          <%= t(:delete) %>
          </th>
          </tr>
      </thead>
      <tbody>
        <% @generic_families.each do |family| %>
          <tr>
            <td><%= family.name%> </td>
            <td><%= family.code%>
            </td>
            <td><%= family.generic_spares.count%></td>
            <td><%= link_to t(:show), family, class: "" %></td>
            <td><%= link_to t(:delete), family, data: { confirm: '¿Seguro Que Deseas Borrarlo?' } , :method => :delete , class: ""%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/generic_families/new.html.erb
<h1>Nueva <%= GenericFamily.model_name.human %></h1>
<% #to do breadcrumbs %>
<%= render 'form' %>

app/views/generic_families/not_assigned.html.erb
<h1>Familias genéricas</h1>


<%= form_tag assign_generic_families_path do | f | %>

	<table id="assignation_table" class="table big_table">
	    <thead>
	        <tr>
	            <th>Nombre Familia</th>
	            <% @car_types.each do | type | %>
	            	<th> <%= type.name %> <%= type.doors %></th>
	            <% end %>
	        </tr>
	    </thead>
	    <tbody>
		    <% @generic_families.each do | family | %>
		    	<tr>
		           <td><%= family.name %></td>
		           <% for type in @car_types do %>
		           	<td><%= check_box_tag 'family_ids[]', "#{family.id},#{type.id}"%></td>
		           <% end %>
	 		  </tr>
		    <% end %>
    	</tbody>
	</table>


	<%= submit_tag "Actualizar Familias", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
	
$( document ).ready(function() {
	$('#assignation_table').DataTable({});
});

</script>

app/views/generic_families/not_assigned_families.html.erb
<h1>Familias genéricas</h1>


<%= form_tag assign_generic_families_path do | f | %>

	<table id="assignation_table" class="table big_table">
	    <thead>
	        <tr>
	            <th>Nombre Familia</th>
	            <% @car_types.each do | type | %>
	            	<th> <%= type.name %> <%= type.doors %></th>
	            <% end %>
	        </tr>
	    </thead>
	    <tbody>

	    <!-- each family -->
			    <% @generic_families.each do | family | %>
			    	<tr>

			           <td><%= family.name %></td>
			           <% for type in @car_types do %>
			           	<td><%= check_box_tag 'family_ids[]', "#{family.id},#{type.id}"%></td>
			           <% end %>
		 		  </tr>
			    <% end %>



    	</tbody>
	</table>


	<%= submit_tag "Actualizar Familias", class: "btn btn-primary" %>
<% end %>