config/routes.rb
LotsoBear::Application.routes.draw do

  resources :supplier_types

  resources :type_likelihoods

  resources :services

  resources :stock_cars

  root 'sessions#new'

  resources :brands
  resources :mold_spares
  resources :model_acronyms
  resources :sessions, only: [:new, :create, :destroy]
  resources :prevaluations, only: [:new, :create, :show]
  resources :valuations, only: [:index, :new, :create, :show]
  resources :spares, only: [:index, :new, :create, :show, :edit ,:destroy, :update]
  resources :generic_spares, only: [:index, :new, :create, :show, :edit ,:destroy, :update]

  get '/supplies/consumer', to: 'supplies#consumer', as: 'consumer_supplies' #getting the user
  get '/supplies/spend/:user_code', to: 'supplies#spend', as: 'spend_fail_supplies' #supplies to spend are listed
  post '/supplies/spend', to: 'supplies#spend', as: 'spend_supplies' #supplies to spend are listed
  post '/supplies/add_supply_to_spend/', to: 'supplies#add_supply_to_spend', as:'add_supply_to_spend' #adds a single supply to spend via ajax
  post '/supplies/update_spend/', to:'supplies#update_spend', as: 'udpate_spend_supplies'
  resources :supplies do
  end

  get '/suppliers/:supplier_id/generic_families/:generic_family_id/new_supplier_code', to: 'supplier_codes#new', as: 'new_supplier_code'
  post '/suppliers/:supplier_id/generic_families/:generic_family_id/supplier_code_creation', to: 'supplier_codes#create', as: 'supplier_generic_family_supplier_codes'
  get '/suppliers/:supplier/add_supplier_codes/:generic_car', to: 'suppliers#add_codes', as: 'add_codes_supplier'
  get "/suppliers/:supplier/download_template/:generic_car", to: "suppliers#download_template", as: 'download_template'
  post "/:supplier/import/:generic_car", to: "suppliers#import", as: "import_suppliers"
  resources :suppliers do
  end

  get 'shelves/:code/store_stocks', to: 'shelves#store_stocks', as: 'get_store_stocks_shelf'

  get 'shelves/search', to: 'shelves#search', as: 'shelves_search'
  post 'shelves/store_stocks', to: 'shelves#store_stocks', as: 'store_stocks_shelf'
  post 'shelves/save_stocks', to: 'shelves#save_stocks', as: 'save_stocks_shelf'
  resources :warehouses do
      get 'shelves/new_bulk', to: 'shelves#new_bulk', as: 'shelves_bulk_new'
      post 'shelves/create_bulk', to: 'shelves#create_bulk', as: 'shelves_bulk_create'
      resources :shelves, shallow: true do
      end
  end

  post 'stock_families/print_label', to: 'stock_families#print_label', as: 'print_label_stock_family'
  post 'stock_families/search', to: 'stock_families#search', as: 'search_stock_family'
  resources :stock_families, only: [:index, :new, :show, :edit ,:destroy, :update] do
    member do
      post :print_label
      get :history
      get :choose_labels
    end
  end

  resources :stock_spares, only: [:edit,:show,:update] do
    member do
      get :history
    end
  end

  resources :orders do
    member do
      post :print_label
      get :history
    end
  end

  post 'generic_families/create_variant', to: 'generic_families#create_variant', as: 'create_variant_stock_family'
  get 'generic_families/:id/variant/:generic_car_id', to: 'generic_families#variant', as: 'variant_generic_family'
  get 'generic_families/:id/edit/:generic_car_id', to: 'generic_families#edit', as: 'edit_generic_family'
  get 'generic_families/remove/:id/', to: 'generic_families#destroy', as: 'delete_generic_family'

  resources :generic_families, only: [:index, :new, :create, :show, :destroy, :update] do
    collection do
      get :not_assigned
      get :assigned
      post :assign
    end
    member do
      get :count_spares
      get :prices
      get :assign_car_type
    end
  end

get "generic_cars/search_generic_car_models/:supplier", to: "generic_cars#search_by_model_in_supplier", as: 'search_by_model_in_supplier'
  resources :generic_cars do
    member do
      get :edit_generation
      get :assignation
      patch :relate_generic_family
      get :update_gen
    end
    collection do
      get :update_generation
      post :search_by_model
    end
  end

    get '/select_generic_families/:id', to: 'inventories#show_generic_car_generic_families', as: 'family_selection'
    get '/inventories/:family_id/:car_id/add_family_with_spares_to_order',to: 'inventories#add_family_with_spares_to_order'
  resources :inventories do
    member do
      get :add_family_with_spares_to_order
    end
    collection do
      get :departure
      get :all
      post :search_stock
      get :search_stock
      post :add_to_inventory, to: 'stock_families#create'
      post :departure_stock_family
      resources :stock_families, only: [:create]
      resources :supplies
    end
  end

  match '/consultar',            to: 'client_actions#home', via: 'get'
  match '/c/show',               to: 'client_actions#show', via: 'get'
  match '/get_client_car', to: 'client_actions#get_client_car', via: 'post'
  match '/admin/suppliers/',    to: 'suppliers#index',        via: 'get'
  match "/admin/attendance", to: 'admin#attendance', via: :get,  as: :attendances
  match '/user/update_attendances', to: 'users#update_attendances', via: :post, as: :import_attendances
  match '/user/:id/attendances', to: 'users#attendances', via: :get, as: :user_attendances

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/download_delays', to: 'users#download_delays', via: 'get', as: :download_delays
  resources :users do
    collection do
      get :spending
    end
    member do
      get :spending_history
    end
  end

namespace :admin do
    get :prices
end

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/model_acronym.rb
# -*- encoding : utf-8 -*-
class ModelAcronym < ActiveRecord::Base
  #Associations
  belongs_to :brand
  has_many :generic_cars

  #Validations
  validates :model, :initials, :brand_id, presence: true

  # validates_uniqueness_of :model, :scope => :brand_id
  validates :model, uniqueness: true
  validate :brand_with_initials_uniqueness

  #CallBakcks
  before_save :upcase

  #Methods
  def self.return_model(brand_id,model)
    where(:brand_id => brand_id, model: model).first
  end

  def model_already_exists?
    ModelAcronym.exists?(:brand_id => brand_id, model: model)
  end

  private
    def upcase
      self.initials.upcase!
      self.model.upcase!
    end
    #Custom Validations
    def brand_with_initials_uniqueness
      if ModelAcronym.exists?(:brand_id => brand_id, model: model,:initials => initials)
      # if ModelAcronym.exists?(:brand_id => brand_id, model: model,:initials => initials)
        return false
      elsif ModelAcronym.exists?(:brand_id => brand_id,:initials => initials)
        errors.add(:initials, "Ya Existen")
      end
    end

end

app/controllers/model_acronyms_controller.rb
# -*- encoding : utf-8 -*-
class ModelAcronymsController < ApplicationController
  before_action :set_model_acronym, only: [:show, :edit, :update, :destroy]

  # GET /model_acronyms
  # GET /model_acronyms.json
  def index
    @model_acronyms = ModelAcronym.all
  end

  # GET /model_acronyms/1
  # GET /model_acronyms/1.json
  def show
  end

  # GET /model_acronyms/new
  def new
    @model_acronym = ModelAcronym.new
  end

  # GET /model_acronyms/1/edit
  def edit
  end

  # POST /model_acronyms
  # POST /model_acronyms.json
  def create
    @model_acronym = ModelAcronym.new(model_acronym_params)

    respond_to do |format|
      if @model_acronym.save
        format.html { redirect_to @model_acronym, notice: 'Model acronym was successfully created.' }
        format.json { render action: 'show', status: :created, location: @model_acronym }
      else
        format.html { render action: 'new' }
        format.json { render json: @model_acronym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /model_acronyms/1
  # PATCH/PUT /model_acronyms/1.json
  def update
    respond_to do |format|
      if @model_acronym.update(model_acronym_params)
        format.html { redirect_to @model_acronym, notice: 'Model acronym was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @model_acronym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /model_acronyms/1
  # DELETE /model_acronyms/1.json
  def destroy
    @model_acronym.destroy
    respond_to do |format|
      format.html { redirect_to model_acronyms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model_acronym
      @model_acronym = ModelAcronym.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_acronym_params
      params.require(:model_acronym).permit(:brand_id, :initials, :model)
    end
end

app/helpers/model_acronyms_helper.rb
# -*- encoding : utf-8 -*-
module ModelAcronymsHelper
end

app/views/model_acronyms/_form.html.erb
<%= form_for(@model_acronym) do |f| %>
  <% if @model_acronym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model_acronym.errors.count, "error") %> prohibited this model_acronym from being saved:</h2>

      <ul>
      <% @model_acronym.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Marca" %><br>
    <%= f.select :brand_id, Brand.all.collect{|p| [ p.name, p.id ] }, {include_blank: '---'} %>
  </div>
  <div class="field">
    <%= f.label "Iniciales" %><br>
    <%= f.text_field :initials %>
  </div>

  <div class="field">
    <%= f.label "Modelo" %><br>
    <%= f.text_field :model %>
  </div>
  <div class="actions">
    <%= f.submit "Crear Iniciales" %>
  </div>
<% end %>

app/views/model_acronyms/edit.html.erb
<h1>Editing model_acronym</h1>

<%= render 'form' %>

<%= link_to 'Show', @model_acronym %> |
<%= link_to 'Back', model_acronyms_path %>

app/views/model_acronyms/index.html.erb
<h1>Listando Todos los Modelos</h1>
<%= link_to 'Nuevo Modelo', new_model_acronym_path, class: "btn btn-primary" %>
<table id="models">
  <thead>
    <tr>
      <th>Marca</th>
      <th>Iniciales</th>
      <th>Modelo</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @model_acronyms.each do |model_acronym| %>
      <tr>
        <td><%= model_acronym.brand.name %></td>
        <td><%= model_acronym.initials %></td>
        <td>
            <%= model_acronym.model %>

        </td>
        <td><%= link_to 'Editar Modelo', edit_model_acronym_path(model_acronym),class: "btn btn-info" %></td>
        <td><%= link_to 'Borrar', model_acronym, method: :delete, data: { confirm: '¿Estas Seguro?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script type="text/javascript">
  $('#models').DataTable({});
</script>

app/views/model_acronyms/new.html.erb
<h1>Nuevas Iniciales</h1>

<%= render 'form' %>

<%= link_to 'Back', model_acronyms_path %>

app/views/model_acronyms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @model_acronym.brand_id %>
</p>

<p>
  <strong>Initials:</strong>
  <%= @model_acronym.initials %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @model_acronym.model %>
</p>

<%= link_to 'Edit', edit_model_acronym_path(@model_acronym) %> |
<%= link_to 'Back', model_acronyms_path %>